imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

rms_push_notifications:
  android:
#      c2dm:
#          username: <string_android_c2dm_username>
#          password: <string_android_c2dm_password>
#          source: <string_android_c2dm_source>
      gcm:
          api_key: xxx
          use_multi_curl: true # default
#  ios:
#      sandbox: <bool_use_apns_sandbox>
#      pem: <path_apns_certificate> # can be absolute or relative path (from app directory)
#      passphrase: <string_apns_certificate_passphrase>
#  mac:
#      sandbox: <bool_use_apns_sandbox>
#      pem: <path_apns_certificate>
#      passphrase: <string_apns_certificate_passphrase>
#  blackberry:
#      evaluation: <bool_bb_evaluation_mode>
#      app_id: <string_bb_app_id>
#      password: <string_bb_password>